### ISSUE TITLE
Duke CS Cluster Java default version

### ISSUE THREAD

**Issue by gusennan** [donaldlab/OSPREY3#104]
The default java version on the CS clusters seems to have changed from 8 to 11.  This is great--allows for taking advantage of nicer language features and is faster, but some of the code is java-8 dependent and needs to be updated.  In particular, two areas that I've found changed are:

1) references to specific names of the GC need to be updated.  I've done this in my fork here:

https://github.com/gusennan/osprey/blob/c4d26fee0fd5724457e9af46aee75532e0890508/src/main/java/edu/duke/cs/osprey/tools/JvmMem.java

2) Update the JavaFX stuff.  This seems to work for me, but I haven't run the code:

https://github.com/gusennan/osprey/blob/master/build.gradle#L1
https://github.com/gusennan/osprey/blob/master/build.gradle#L36

**Comment by cuchaz** [comment]
Looks great! I don't see any harm in supporting the newer v11 JVMs. As long as we can still maintain compatibility with the older v8 JVMs. From what I understand, lots of people haven't really upgraded to v11 yet.

**Comment by gusennan** [comment]
Since we're not getting paid by our users, my opinion is that we should be using the tools and paradigms that make it easiest for us to develop and ship the software.  We have version control if people need to use a previous version.

The lab desktop computers don't even have Java 8 installed on them.

**Comment by gusennan** [comment]
This isn't an issue anymore that we use jpackage.
