### ISSUE TITLE
Tips for Getting ACE and N-Methyl Templates

### ISSUE THREAD

**Issue by hnisonoff** [donaldlab/OSPREY3#126]
I would like to include N- and C-terminal caps in my designs (acetyl group / ACE for N-terminus and N-methyl for the C-terminus). Do you have any guidance on how to generate the appropriate templates for these?
Thanks!

**Comment by cuchaz** [comment]
I honestly have no idea how to do it on the original conf space system. You might try the osprey mailing list instead of GitHub. More of the designers pay attention there.

**Comment by hnisonoff** [comment]
Got it, no problem! Looking forward to the new release!

**Comment by gusennan** [comment]
Hey @hnisonoff 

I'm going to close this, but feel free to email us if you'd like to discuss (osprey@cs.duke.edu).  Here's generally how you can generate templates:

Choice 1: Use ospreyprep.com on your structure.  It should generate all templates that Osprey doesn't currently support but are needed for your structure.  It has a high-failure rate though, and it's unsupported.

Choice 2: Use amber and ambertools.  In ambertools templates are called topology files.  I've attached fish scripts I used with Ambertools 19 to generate topology files and topology coordinates for the kemp eliminase system I was working on. 

Choice 3: Try out the new [osprey gui](https://github.com/donaldlab/osprey-gui).  It's still beta, but we're interested in feedback.  You can download from the build server for macOS.  See https://github.com/donaldlab/osprey-gui/issues/12 for a work-around if the package "is damaged and can't be opened" on Catalina.  

[prep.zip](https://github.com/donaldlab/OSPREY3/files/4708042/prep.zip)

**Comment by hnisonoff** [comment]
Hi Nate,

Thanks so much for the help. I can't seem to find the download from the
build server. This is what I see when I hit the link for the build server:
[image: image.png]

Best,
Hunter

**Comment by gusennan** [comment]
Hey Hunter, 

For whatever reason, I can't see your image here on GitHub.  Maybe because reply thru email?

Here's the direct link. https://dev.azure.com/donaldlab/osprey/_build/results?buildId=48&view=artifacts&type=publishedArtifacts

**Comment by hnisonoff** [comment]
Yeah that was through email, my bad! This is great, thanks!
