### ISSUE TITLE
How to add osprey to path?

### ISSUE THREAD

**Issue by AlirezaDoustmohammadi** [donaldlab/OSPREY3#138]
Hello.
How to add osprey to the path? I want to add permission for all users to use osprey.

**Comment by cuchaz** [comment]
Osprey is packaged as a Python module, so hopefully everywhere your users can use Python, they can also use Osprey?

**Comment by AlirezaDoustmohammadi** [comment]
I install it by root user and I get 'No module named 'osprey' error when I run osprey scripts by other user accounts.

**Comment by cuchaz** [comment]
Maybe try [this solution](https://stackoverflow.com/a/36898870)?

> Use the `--target` option when calling pip

```
pip install --target=/your/pyinstalldir osprey
```

And pick the system python package folder as the `--target`. Maybe that will work?

**Comment by gusennan** [comment]
@AlirezaDoustmohammadi did this resolve your issue?

**Comment by gusennan** [comment]
Closing.  @AlirezaDoustmohammadi please let us know if this continues to be an issue for you.

**Comment by AlirezaDoustmohammadi** [comment]
this issue solving by changing install.sh file according to @cuchaz solution:

#! /bin/sh
python -m pip uninstall -y osprey JPype-py2
python -m pip install --target=python site-packages directory  'numpy>=1.6,<1.16'
python -m pip install --target=python site-packages directory  osprey --no-index --find-link=wheelhouse --pre

thanks a lot @cuchaz
