### ISSUE TITLE
install.sh for osprey

### ISSUE THREAD

**Issue by biotech70** [donaldlab/OSPREY3#149]
I want to install the osprey using the ./install.sh command but this file is not in the download folder. please guide me
![Untitled](https://user-images.githubusercontent.com/73783725/99786369-a4043e00-2b33-11eb-8bbf-1ec2fbc576c0.png)

**Comment by cuchaz** [comment]
Try downloading a release from here:

https://github.com/donaldlab/OSPREY3/releases/tag/3.2.101

**Comment by gusennan** [comment]
Closing as we resolved in #150
