### ISSUE TITLE
osprey runing error

### ISSUE THREAD

**Issue by biotech70** [donaldlab/OSPREY3#150]
H
![1](https://user-images.githubusercontent.com/73783725/99854330-d9dc0d80-2b99-11eb-8598-b9093d472a6b.png)
![2](https://user-images.githubusercontent.com/73783725/99854334-df395800-2b99-11eb-9a17-2d8651885af0.png)

i. during running and work with osprey i get this error, what is problem and how its can be solved

**Comment by biotech70** [comment]
To be, or not to be, that is the question. No one to help me?

**Comment by gusennan** [comment]
Hi! What version of Osprey are you using? From where did you download it?

**Comment by gusennan** [comment]
@cuchaz noticed this commit. Do you think it's relevant? 

https://github.com/donaldlab/OSPREY3/commit/9419e5305d56d173353af9d59377a143de3cbd17

**Comment by biotech70** [comment]
thanks for your response. i download it from this address, https://github.com/donaldlab/OSPREY3/releases/tag/3.2.101

**Comment by biotech70** [comment]
> @cuchaz noticed this commit. Do you think it's relevant?
> 
> [9419e53](https://github.com/donaldlab/OSPREY3/commit/9419e5305d56d173353af9d59377a143de3cbd17)


I do not understand

**Comment by cuchaz** [comment]
@gusennan Ah, yes. This bug was fixed in a later release. But somehow that release is not the newest release that's publicly available on the GitHub releases page.

**Comment by biotech70** [comment]
How can I download the new version?

**Comment by biotech70** [comment]
please guide me

**Comment by cuchaz** [comment]
Oh wait, here's a "pre" release that contains the fix. I think that one is publicly available? Try downloading this one:

https://github.com/gusennan/osprey2/blob/master/src/main/java/Amber96ext.java#L1442

Sorry, our release system is kind of confusing now.

**Comment by biotech70** [comment]
> Oh wait, here's a "pre" release that contains the fix. I think that one is publicly available? Try downloading this one:
> 
> https://github.com/donaldlab/OSPREY3/releases/tag/3.2.203
> 
> Sorry, our release system is kind of confusing now.

Which one should be downloaded and how should we install it?
![Untitled](https://user-images.githubusercontent.com/73783725/100005690-99b99c80-2dde-11eb-8b73-09f1c32b5c89.png)

**Comment by cuchaz** [comment]
I'm sorry... I don't actually know. =(

@gusennan Any ideas? That release doesn't seem to have the right downloadable files.

**Comment by biotech70** [comment]
I downloaded but I do not know how to install it

**Comment by biotech70** [comment]
This is a great regret

**Comment by gusennan** [comment]
@cuchaz I can promote the current latest pre-release to be an official release.

**Comment by biotech70** [comment]
> @cuchaz I can promote the current latest pre-release to be an official release.

okey Please share my error with your friends

**Comment by cuchaz** [comment]
@gusennan Will that fix the issue with the release files? What's a shadow file? What happened to the os/python zip files in the release?

**Comment by gusennan** [comment]
I missed that comment.  Here's a pre-release with the latest:

https://github.com/donaldlab/OSPREY3/releases/tag/3.2.213

@biotech70 download the appropriate package for your OS in this release and follow the instructions in the README on the page to install.

**Comment by cuchaz** [comment]
That looks good to me. Thanks for fixing it, @gusennan ! =)

**Comment by biotech70** [comment]
> I missed that comment. Here's a pre-release with the latest:
> 
> https://github.com/donaldlab/OSPREY3/releases/tag/3.2.213
> 
> @biotech70 download the appropriate package for your OS in this release and follow the instructions in the README on the page to install.

Which one should be downloaded (my system is ubuntu 20.04) and how should we install it?
![Untitled](https://user-images.githubusercontent.com/73783725/100115755-240a0b00-2e88-11eb-9500-53a377d395b0.png)

**Comment by cuchaz** [comment]
You should download one of the "linux" versions. Of those two, pick the one that matches your version of Python. Then follow the install instructions here: https://github.com/donaldlab/OSPREY3#on-linux

**Comment by biotech70** [comment]
> You should download one of the "linux" versions. Of those two, pick the one that matches your version of Python. Then follow the install instructions here: https://github.com/donaldlab/OSPREY3#on-linux

thanks thanks thanks ho ho im very happy. where can i find osprey tutorial?

**Comment by cuchaz** [comment]
I'm glad you got it working! =D

We don't have much of a tutorial, but you can find a very basic one at `doc/tutorial.html` inside the zip file you just downloaded.

**Comment by gusennan** [comment]
Glad to hear it too. Closing issue for now, feel free to re-open if need be.
