### ISSUE TITLE
install osprey in windows

### ISSUE THREAD

**Issue by biotech70** [donaldlab/OSPREY3#152]
hello dear friends. i try to install osprey in windows 8.1 but get followed error. please guide me.
![1](https://user-images.githubusercontent.com/73783725/101079981-73091c00-35bd-11eb-846a-4451e82d9212.png)

**Comment by cuchaz** [comment]
Hello. It looks like JPype (a library that Osprey uses) wants to compile itself on your computer. To enable it to compile, it looks like you'll have to install Visual Studio at the link suggested in the error message.

Osprey provides pre-compiled versions of JPype in the installer, but they only work on 64 bit versions of Windows. We've tested this on Windows 10, but we've never tested Windows 8, so we're not sure if that would work in your case.

**Comment by gusennan** [comment]
Please try on Windows 10 or a supported Linux system.  We don't support Windows 8. Feel free to reopen if you have any remaining questions.
