### ISSUE TITLE
templateLib

### ISSUE THREAD

**Issue by biotech70** [donaldlab/OSPREY3#153]
hello dear friends. i try to do osprey for a complex of protein-protein, But I do not know the role of the specified part in the script. Please guide me.
![Untitled](https://user-images.githubusercontent.com/73783725/101208388-5e915600-3687-11eb-81ec-63c203b68120.png)

**Comment by cuchaz** [comment]
Hello, line 15 in that script extracts a portion of the PDB file (specifically residues `G648` through `G654` from the `mol` object) into a `Strand` object to which Osprey can attach flexibility information (eg, lines 16-19).

Those `Strand` objects then can be composed into the states of your COMETS design. See lines 29-30.

Hope that helps!

**Comment by gusennan** [comment]
For future reference, Osprey has an email list that general questions can be emailed to: osprey@cs.duke.edu.

Closing as resolved.
