### ISSUE TITLE
memory size

### ISSUE THREAD

**Issue by biotech70** [donaldlab/OSPREY3#154]
hi dear friends. How can I increase the size of memory in water?
![Untitled](https://user-images.githubusercontent.com/73783725/101521931-bb4c8380-399b-11eb-8456-50a9eb4746e0.png)

I also use the following comment to increase the speed of the osprey, but the power of 5 cores of cpu and gpu is not used:
parallelism = osprey.Parallelism(cpuCores=2, gpus=1, streamsPerGpu=1)

**Comment by cuchaz** [comment]
Hello. The docs in the zip file you downloaded have more information about extra options and settings. Try looking at `doc/api.osprey.html`.

Except: it looks like the docs aren't being generated correctly somehow by the new build system. Sorry about that. Instead, you can try reading the doc sources to get the same info. Here's the sources that match your build of Osprey:

https://github.com/donaldlab/OSPREY3/blob/f5b765fb9cd9fac8f85298fb5e2387fb6e5506ce/python/osprey/__init__.py#L212

In this case, you specifically want the `heapSizeMiB` option here:

https://github.com/donaldlab/OSPREY3/blob/f5b765fb9cd9fac8f85298fb5e2387fb6e5506ce/python/osprey/__init__.py#L218

**Comment by gusennan** [comment]
Question answered. Closing issue.
