### ISSUE TITLE
forcefield file missing

### ISSUE THREAD

**Issue by shengzizhang** [donaldlab/OSPREY3#173]
I installed the newest python version of osprey and ran into the following error when running the example script, see below. Could you help figure out what happened with the forcefield parameter missing?

###############
Python 3.7.0 (default, Oct  9 2020, 13:46:11) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import osprey
>>> 
>>> osprey.start()
WARNING: Using incubator modules: jdk.incubator.foreign
OSPREY 3.2.289, Python 3.7.0, Java 16.0.1, Linux-3.10.0-862.14.4.el7.x86_64-x86_64-with-centos-7.5.1804-Core
Using up to 1024 MiB heap memory: 128 MiB for garbage, 896 MiB for storage
>>> strand = osprey.Strand('1CC8.ss.pdb')
read PDB file from file: 1CC8.ss.pdb
>>> strand.flexibility['A2'].setLibraryRotamers('ALA', 'GLY')
<java object 'edu.duke.cs.osprey.confspace.Strand.ResidueFlex'>
>>> strand.flexibility['A3'].setLibraryRotamers(osprey.WILD_TYPE, 'VAL')
<java object 'edu.duke.cs.osprey.confspace.Strand.ResidueFlex'>
>>> strand.flexibility['A4'].setLibraryRotamers(osprey.WILD_TYPE)
<java object 'edu.duke.cs.osprey.confspace.Strand.ResidueFlex'>
>>> confSpace = osprey.ConfSpace(strand)
>>> ffparams = osprey.ForcefieldParams()
Traceback (most recent call last):
  File "ForcefieldParams.java", line 256, in edu.duke.cs.osprey.energy.forcefield.ForcefieldParams.<init>
Exception: Java Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zs/.local/lib/python3.7/site-packages/osprey/__init__.py", line 584, in ForcefieldParams
    return c.energy.forcefield.ForcefieldParams(Forcefield.AMBER, params)
java.lang.NullPointerException: java.lang.NullPointerException: Cannot invoke "edu.duke.cs.osprey.energy.forcefield.amber.ForcefieldFileParser.read()" because "parameterFile" is null

**Comment by gusennan** [comment]
@shengzizhang, thank you for reporting this. I've released a new version, 3.2.304, that fixes this issue. Please try it out and let us know if you run into any issues.
