### ISSUE TITLE
Java package 'edu.duke.cs.osprey' has no attribute 'confspace' when compiling from source

### ISSUE THREAD

**Issue by ONikeH** [donaldlab/OSPREY3#182]
Hi I have compiled OSPREY3 from source on ubuntu 20.04. When I run osprey.start() I get the following error:
>>> import osprey
>>> osprey.start()
WARNING: Using incubator modules: jdk.incubator.foreign
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vlad/Desktop/Test_Osprey_Che/OSPREY3/src/main/python/osprey/__init__.py", line 249, in start
    _start_jvm_common(lambda jre_path: jvm.start(jre_path, heapSizeMiB, enableAssertions, stackSizeMiB, garbageSizeMiB, allowRemoteManagement, attachJvmDebugger))
  File "/home/vlad/Desktop/Test_Osprey_Che/OSPREY3/src/main/python/osprey/__init__.py", line 179, in _start_jvm_common
    wraps.init(c)
  File "/home/vlad/Desktop/Test_Osprey_Che/OSPREY3/src/main/python/osprey/wraps.py", line 66, in init
    wrapStrandFlex(c)
  File "/home/vlad/Desktop/Test_Osprey_Che/OSPREY3/src/main/python/osprey/wraps.py", line 111, in wrapStrandFlex
    jtype = jvm.getInnerClass(c.confspace.Strand, 'Flexibility')
AttributeError: Java package 'edu.duke.cs.osprey' has no attribute 'confspace'

Appreciate any help fixing this issue.

java output:
$ java -version
openjdk version "17.0.3" 2022-04-19
OpenJDK Runtime Environment Temurin-17.0.3+7 (build 17.0.3+7)
OpenJDK 64-Bit Server VM Temurin-17.0.3+7 (build 17.0.3+7, mixed mode, sharing)

**Comment by a269ch** [comment]
I have got the same error. @cuchaz сould you help me?

**Comment by gusennan** [comment]
Sorry for not seeing this earlier. Please re-open if it's still an issue and if you continue to need help.

**Comment by ONikeH** [comment]
Still have an issue while compiling from source: 
$ java -version
openjdk version "11.0.17" 2022-10-18
OpenJDK Runtime Environment (build 11.0.17+8-post-Ubuntu-1ubuntu220.04)
OpenJDK 64-Bit Server VM (build 11.0.17+8-post-Ubuntu-1ubuntu220.04, mixed mode, sharing)

$ git clone https://github.com/donaldlab/OSPREY3.git

$ ./gradlew pythonDevelop

> Task :buildSrc:compileKotlin
'compileJava' task (current target is 11) and 'compileKotlin' task (current target is 1.8) jvm target compatibility should be set to the same Java version.
w: Runtime JAR files in the classpath should have the same version. These files were found in the classpath:
    /root/.gradle/wrapper/dists/gradle-7.3-bin/ddwl0k7mt9g6ak16i1m905vyv/gradle-7.3/lib/kotlin-stdlib-1.5.31.jar (version 1.5)
    /root/.gradle/wrapper/dists/gradle-7.3-bin/ddwl0k7mt9g6ak16i1m905vyv/gradle-7.3/lib/kotlin-stdlib-common-1.5.31.jar (version 1.5)
    /root/.gradle/wrapper/dists/gradle-7.3-bin/ddwl0k7mt9g6ak16i1m905vyv/gradle-7.3/lib/kotlin-stdlib-jdk7-1.5.31.jar (version 1.5)
    /root/.gradle/wrapper/dists/gradle-7.3-bin/ddwl0k7mt9g6ak16i1m905vyv/gradle-7.3/lib/kotlin-stdlib-jdk8-1.5.31.jar (version 1.5)
    /root/.gradle/wrapper/dists/gradle-7.3-bin/ddwl0k7mt9g6ak16i1m905vyv/gradle-7.3/lib/kotlin-reflect-1.5.31.jar (version 1.5)
    /root/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk8/1.6.10/e80fe6ac3c3573a80305f5ec43f86b829e8ab53d/kotlin-stdlib-jdk8-1.6.10.jar (version 1.6)
    /root/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-reflect/1.5.31/1523fcd842a47da0820cea772b19c51056fec8a9/kotlin-reflect-1.5.31.jar (version 1.5)
    /root/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk7/1.6.10/e1c380673654a089c4f0c9f83d0ddfdc1efdb498/kotlin-stdlib-jdk7-1.6.10.jar (version 1.6)
    /root/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.6.10/b8af3fe6f1ca88526914929add63cf5e7c5049af/kotlin-stdlib-1.6.10.jar (version 1.6)
    /root/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.6.10/c118700e3a33c8a0d9adc920e9dec0831171925/kotlin-stdlib-common-1.6.10.jar (version 1.6)
w: Consider providing an explicit dependency on kotlin-reflect 1.6 to prevent strange errors
w: Some runtime JAR files in the classpath have an incompatible version. Consider removing them from the classpath
w: Some JAR files in the classpath have the Kotlin Runtime library bundled into them. This may cause difficult to debug problems if there's a different version of the Kotlin Runtime library in the classpath. Consider removing these libraries from the classpath
w: /root/.gradle/caches/modules-2/files-2.1/org.jetbrains.dokka/kotlin-analysis-compiler/1.6.10/e08b1c2b4c60ec5fc8b14a148bf1e39058e1d681/kotlin-analysis-compiler-1.6.10.jar: Library has Kotlin runtime bundled into it
w: /root/.gradle/caches/modules-2/files-2.1/org.jetbrains.dokka/kotlin-analysis-intellij/1.6.10/44adb96d6c20f276642a5f7236796c4477a9b4ed/kotlin-analysis-intellij-1.6.10.jar: Library has Kotlin runtime bundled into it
w: /home/<user>/Test_Osprey_Che/February2023/OSPREY3/buildSrc/src/main/kotlin/osprey/build/desktop.kt: (142, 6): Variable 'desktopRelease' is never used
w: /home/<user>/Test_Osprey_Che/February2023/OSPREY3/buildSrc/src/main/kotlin/osprey/docs.kt: (250, 6): Variable 'buildDocsRelease' is never used
w: /home/<user>/Test_Osprey_Che/February2023/OSPREY3/buildSrc/src/main/kotlin/osprey/docs.kt: (564, 8): Name shadowed: webDir

> Task :buildSrc:compileJava FAILED
/home/<user>/Test_Osprey_Che/February2023/OSPREY3/buildSrc/src/main/java/osprey/JavadocTool.java:151: error: ')' expected
                                if (type instanceof ClassTree classType) {
                                                             ^
/home/<user>/Test_Osprey_Che/February2023/OSPREY3/buildSrc/src/main/java/osprey/JavadocTool.java:151: error: not a statement
                                if (type instanceof ClassTree classType) {
                                                              ^
/home/<user>/Test_Osprey_Che/February2023/OSPREY3/buildSrc/src/main/java/osprey/JavadocTool.java:151: error: ';' expected
                                if (type instanceof ClassTree classType) {
                                                                       ^
/home/<user>/Test_Osprey_Che/February2023/OSPREY3/buildSrc/src/main/java/osprey/JavadocTool.java:181: error: ')' expected
                        if (member instanceof VariableTree variableMember) {
                                                          ^
/home/<user>/Test_Osprey_Che/February2023/OSPREY3/buildSrc/src/main/java/osprey/JavadocTool.java:181: error: not a statement
                        if (member instanceof VariableTree variableMember) {
                                                           ^
/home/<user>/Test_Osprey_Che/February2023/OSPREY3/buildSrc/src/main/java/osprey/JavadocTool.java:181: error: ';' expected
                        if (member instanceof VariableTree variableMember) {
                                                                         ^
/home/<user>/Test_Osprey_Che/February2023/OSPREY3/buildSrc/src/main/java/osprey/JavadocTool.java:183: error: ')' expected
                        } else if (member instanceof MethodTree methodMember) {
                                                               ^
/home/<user>/Test_Osprey_Che/February2023/OSPREY3/buildSrc/src/main/java/osprey/JavadocTool.java:183: error: not a statement
                        } else if (member instanceof MethodTree methodMember) {
                                                                ^
/home/<user>/Test_Osprey_Che/February2023/OSPREY3/buildSrc/src/main/java/osprey/JavadocTool.java:183: error: ';' expected
                        } else if (member instanceof MethodTree methodMember) {
                                                                            ^
/home/<user>/Test_Osprey_Che/February2023/OSPREY3/buildSrc/src/main/java/osprey/JavadocTool.java:183: error: 'else' without 'if'
                        } else if (member instanceof MethodTree methodMember) {
                          ^
/home/<user>/Test_Osprey_Che/February2023/OSPREY3/buildSrc/src/main/java/osprey/JavadocTool.java:185: error: ')' expected
                        } else if (member instanceof ClassTree classMember) {
                                                              ^
/home/<user>/Test_Osprey_Che/February2023/OSPREY3/buildSrc/src/main/java/osprey/JavadocTool.java:185: error: not a statement
                        } else if (member instanceof ClassTree classMember) {
                                                               ^
/home/<user>/Test_Osprey_Che/February2023/OSPREY3/buildSrc/src/main/java/osprey/JavadocTool.java:185: error: ';' expected
                        } else if (member instanceof ClassTree classMember) {
                                                                          ^
/home/<user>/Test_Osprey_Che/February2023/OSPREY3/buildSrc/src/main/java/osprey/JavadocTool.java:185: error: 'else' without 'if'
                        } else if (member instanceof ClassTree classMember) {
                          ^
/home/<user>/Test_Osprey_Che/February2023/OSPREY3/buildSrc/src/main/java/osprey/JavadocTool.java:278: error: ')' expected
                if (elem instanceof TypeElement typeElem) {
                                               ^
/home/<user>/Test_Osprey_Che/February2023/OSPREY3/buildSrc/src/main/java/osprey/JavadocTool.java:278: error: not a statement
                if (elem instanceof TypeElement typeElem) {
                                                ^
/home/<user>/Test_Osprey_Che/February2023/OSPREY3/buildSrc/src/main/java/osprey/JavadocTool.java:278: error: ';' expected
                if (elem instanceof TypeElement typeElem) {
                                                        ^
/home/<user>/Test_Osprey_Che/February2023/OSPREY3/buildSrc/src/main/java/osprey/JavadocTool.java:283: error: ')' expected
                        if (tree instanceof ParameterizedTypeTree typeTree) {
                                                                 ^
/home/<user>/Test_Osprey_Che/February2023/OSPREY3/buildSrc/src/main/java/osprey/JavadocTool.java:283: error: not a statement
                        if (tree instanceof ParameterizedTypeTree typeTree) {
                                                                  ^
/home/<user>/Test_Osprey_Che/February2023/OSPREY3/buildSrc/src/main/java/osprey/JavadocTool.java:283: error: ';' expected
                        if (tree instanceof ParameterizedTypeTree typeTree) {
                                                                          ^
/home/<user>/Test_Osprey_Che/February2023/OSPREY3/buildSrc/src/main/java/osprey/JavadocTool.java:292: error: 'else' without 'if'
                } else if (elem instanceof TypeParameterElement) {
                  ^
/home/<user>/Test_Osprey_Che/February2023/OSPREY3/buildSrc/src/main/java/osprey/JavadocTool.java:341: error: : expected
                                case "cite" ->
                                           ^
/home/<user>/Test_Osprey_Che/February2023/OSPREY3/buildSrc/src/main/java/osprey/JavadocTool.java:341: error: illegal start of expression
                                case "cite" ->
                                            ^
/home/<user>/Test_Osprey_Che/February2023/OSPREY3/buildSrc/src/main/java/osprey/JavadocTool.java:344: error: : expected
                                case "warning", "warn" ->
                                              ^
/home/<user>/Test_Osprey_Che/February2023/OSPREY3/buildSrc/src/main/java/osprey/JavadocTool.java:347: error: : expected
                                case "note" ->
                                           ^
/home/<user>/Test_Osprey_Che/February2023/OSPREY3/buildSrc/src/main/java/osprey/JavadocTool.java:347: error: illegal start of expression
                                case "note" ->
                                            ^
/home/<user>/Test_Osprey_Che/February2023/OSPREY3/buildSrc/src/main/java/osprey/JavadocTool.java:350: error: : expected
                                case "todo" ->
                                           ^
/home/<user>/Test_Osprey_Che/February2023/OSPREY3/buildSrc/src/main/java/osprey/JavadocTool.java:350: error: illegal start of expression
                                case "todo" ->
                                            ^
/home/<user>/Test_Osprey_Che/February2023/OSPREY3/buildSrc/src/main/java/osprey/JavadocTool.java:353: error: : expected
                                default ->
                                       ^
/home/<user>/Test_Osprey_Che/February2023/OSPREY3/buildSrc/src/main/java/osprey/JavadocTool.java:353: error: illegal start of expression
                                default ->
                                        ^
/home/<user>/Test_Osprey_Che/February2023/OSPREY3/buildSrc/src/main/java/osprey/JavadocTool.java:429: error: ')' expected
                } else if (elem instanceof TypeElement typeElem) {
                                                      ^
/home/<user>/Test_Osprey_Che/February2023/OSPREY3/buildSrc/src/main/java/osprey/JavadocTool.java:429: error: not a statement
                } else if (elem instanceof TypeElement typeElem) {
                                                       ^
/home/<user>/Test_Osprey_Che/February2023/OSPREY3/buildSrc/src/main/java/osprey/JavadocTool.java:429: error: ';' expected
                } else if (elem instanceof TypeElement typeElem) {
                                                               ^
/home/<user>/Test_Osprey_Che/February2023/OSPREY3/buildSrc/src/main/java/osprey/JavadocTool.java:439: error: ')' expected
                } else if (elem instanceof VariableElement varElem) {
                                                          ^
/home/<user>/Test_Osprey_Che/February2023/OSPREY3/buildSrc/src/main/java/osprey/JavadocTool.java:439: error: not a statement
                } else if (elem instanceof VariableElement varElem) {
                                                           ^
/home/<user>/Test_Osprey_Che/February2023/OSPREY3/buildSrc/src/main/java/osprey/JavadocTool.java:439: error: ';' expected
                } else if (elem instanceof VariableElement varElem) {
                                                                  ^
/home/<user>/Test_Osprey_Che/February2023/OSPREY3/buildSrc/src/main/java/osprey/JavadocTool.java:439: error: 'else' without 'if'
                } else if (elem instanceof VariableElement varElem) {
                  ^
/home/<user>/Test_Osprey_Che/February2023/OSPREY3/buildSrc/src/main/java/osprey/JavadocTool.java:443: error: ')' expected
                        if (container instanceof TypeElement containerTypeElem) {
                                                            ^
/home/<user>/Test_Osprey_Che/February2023/OSPREY3/buildSrc/src/main/java/osprey/JavadocTool.java:443: error: not a statement
                        if (container instanceof TypeElement containerTypeElem) {
                                                             ^
/home/<user>/Test_Osprey_Che/February2023/OSPREY3/buildSrc/src/main/java/osprey/JavadocTool.java:443: error: ';' expected
                        if (container instanceof TypeElement containerTypeElem) {
                                                                              ^
/home/<user>/Test_Osprey_Che/February2023/OSPREY3/buildSrc/src/main/java/osprey/JavadocTool.java:445: error: 'else' without 'if'
                        } else {
                          ^
/home/<user>/Test_Osprey_Che/February2023/OSPREY3/buildSrc/src/main/java/osprey/JavadocTool.java:459: error: ')' expected
                } else if (elem instanceof ExecutableElement execElem) {
                                                            ^
/home/<user>/Test_Osprey_Che/February2023/OSPREY3/buildSrc/src/main/java/osprey/JavadocTool.java:459: error: not a statement
                } else if (elem instanceof ExecutableElement execElem) {
                                                             ^
/home/<user>/Test_Osprey_Che/February2023/OSPREY3/buildSrc/src/main/java/osprey/JavadocTool.java:459: error: ';' expected
                } else if (elem instanceof ExecutableElement execElem) {
                                                                     ^
/home/<user>/Test_Osprey_Che/February2023/OSPREY3/buildSrc/src/main/java/osprey/JavadocTool.java:459: error: 'else' without 'if'
                } else if (elem instanceof ExecutableElement execElem) {
                  ^
/home/<user>/Test_Osprey_Che/February2023/OSPREY3/buildSrc/src/main/java/osprey/JavadocTool.java:463: error: ')' expected
                        if (container instanceof TypeElement containerTypeElem) {
                                                            ^
/home/<user>/Test_Osprey_Che/February2023/OSPREY3/buildSrc/src/main/java/osprey/JavadocTool.java:463: error: not a statement
                        if (container instanceof TypeElement containerTypeElem) {
                                                             ^
/home/<user>/Test_Osprey_Che/February2023/OSPREY3/buildSrc/src/main/java/osprey/JavadocTool.java:463: error: ';' expected
                        if (container instanceof TypeElement containerTypeElem) {
                                                                              ^
/home/<user>/Test_Osprey_Che/February2023/OSPREY3/buildSrc/src/main/java/osprey/JavadocTool.java:465: error: 'else' without 'if'
                        } else {
                          ^
/home/<user>/Test_Osprey_Che/February2023/OSPREY3/buildSrc/src/main/java/osprey/JavadocTool.java:491: error: 'else' without 'if'
                } else {
                  ^
50 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':buildSrc:compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 12s
2 actionable tasks: 2 executed
