### ISSUE TITLE
Example Scripts for fries/EWAK*

### ISSUE THREAD

**Issue by amin-sagar** [donaldlab/OSPREY3#191]
Dear Osprey Developers,
I am looking for an implementation of the fries/EWAK* method as presented in [https://doi.org/10.1371/journal.pcbi.1007447](https://doi.org/10.1371/journal.pcbi.1007447).
Is there an example python script which uses this method.
If not, can you please give me some pointers on how to modify the EWAK* script to include FRIES based pruning of the sequence space.
Best,
Amin.

**Comment by alowegard** [comment]
Hello,All of the necessary scripts and code should be available in the data repository directly referenced in the publication: https://doi.org/10.7910/DVN/VHIRNMKind regards,Anna---Anna U. Lowegard, Ph.D.On 30 May 2023, at 13:39, amin-sagar ***@***.***> wrote:﻿
Dear Osprey Developers,
I am looking for an implementation of the fries/EWAK* method as presented in https://doi.org/10.1371/journal.pcbi.1007447.
Is there an example python script which uses this method.
If not, can you please give me some pointers on how to modify the EWAK* script to include FRIES based pruning of the sequence space.
Best,
Amin.

**Comment by amin-sagar** [comment]
Thanks @alowegard 
I looked at the scripts in the repository.
They look very similar to the example ewakstar script at [https://github.com/donaldlab/OSPREY3/blob/main/examples/python.EWAKStar/ewakstar.py](https://github.com/donaldlab/OSPREY3/blob/main/examples/python.EWAKStar/ewakstar.py)

I thought the example ewakstar script would only have ewak* without FRIES.
However, if I understand correctly,
```
# energy window limit for partition function calculation
	pfEw = 1.0,

	# energy window within the wild-type for finding sequences in the "sequence filter" portion of ewakstarDoer
	eW = 30.0,

	# order of magnitude worse in partition function we want to keep sequences relative to the wild-type
	orderOfMag = 10,
```
This part prunes the sequence space and corresponds to the FRIES part.
Am I understanding this correctly?
Best,
Amin.

**Comment by alowegard** [comment]
Hi Amin,Yes, that is correct. Apologies for not being more clear, I have not looked at these scripts in some time. You can see the 30 kcal energy window set and the 10 orders of magnitude for the sequence pruning and this is where FRIES is accounted for. Best,Anna---Anna U. Lowegard, Ph.D.On 01 Jun 2023, at 08:12, amin-sagar ***@***.***> wrote:﻿
Thanks @alowegard
I looked at the scripts in the repository.
They look very similar to the example ewakstar script at https://github.com/donaldlab/OSPREY3/blob/main/examples/python.EWAKStar/ewakstar.py
I thought the example ewakstar script would only have ewak* without FRIES.
However, if I understand correctly,
# energy window limit for partition function calculation
	pfEw = 1.0,

	# energy window within the wild-type for finding sequences in the "sequence filter" portion of ewakstarDoer
	eW = 30.0,

	# order of magnitude worse in partition function we want to keep sequences relative to the wild-type
	orderOfMag = 10,

This part prunes the sequence space and corresponds to the FRIES part.
Am I understanding this correctly?
Best,
Amin.

**Comment by amin-sagar** [comment]
Thanks a lot @alowegard for your help. 
Best,
Amin.
