### ISSUE TITLE
emat.dat file

### ISSUE THREAD

**Issue by ever4cyth** [donaldlab/OSPREY3#46]
Sorry another question. How to access emat.dat file from python? it is a binary file, can we have the option to save it as human readable file? Thanks!

**Comment by jonathanjou** [comment]
Hey there!

You appear to be trying to use our latest code, which has lots of new features, but isn't quite stable yet. Thanks for raising these issues. Can I ask what you plan to use OSPREY for, and what group or school you're affiliated with? I'd be very excited to spread the word and as OSPREY 3.0 becomes feature complete your feedback will be very valuable to us.

How did you discover OSPREY? Would you be able to use the latest stable version, which is OSPREY 2.2 beta, found instead at http://www.cs.duke.edu/donaldlab/osprey.php ?

If you're okay with us getting to your issues a little later this year, I'm glad to have new users trying out our code. That said, we're a small University-run lab, so we may not fix your issues or respond to your requests as quickly as we'd like.

Thanks,
Jonathan
