### ISSUE TITLE
Installation script error

### ISSUE THREAD

**Issue by jkleinj** [donaldlab/OSPREY3#74]
Dear Developers,
thank you for sharing the program.
I have downloaded the latest release (osprey-python-3.0-beta1),
followed the installation instructions (on Linux) and
have encountered the following error:
```
j@ac:~/software/osprey$ ./install.sh 
Skipping JPype-py2 as it is not installed.
Skipping osprey as it is not installed.
Requirement already satisfied: numpy in /usr/local/lib/python2.7/dist-packages (1.12.0)

Usage:   
  pip2 install [options] <requirement specifier> [package-index-options] ...
  pip2 install [options] -r <requirements file> [package-index-options] ...
  pip2 install [options] [-e] <vcs project url> ...
  pip2 install [options] [-e] <local project path> ...
  pip2 install [options] <archive url/path> ...

no such option: --use-wheel
```

Any help would be appreciated,
thanks,
  Jens

**Comment by cuchaz** [comment]
I think newer versions of `pip` have dropped the `--use-wheel` flag. I think the installer will still work without the flag though, so maybe it can be removed from the install script.

We'll work on fixing this in the next version, but you can probably make the change yourself so you don't have to wait on us. Try editing the `install.sh` script from this:
```
pip2 install --user osprey --no-index --use-wheel --find-link=wheelhouse
```
to this
```
pip2 install --user osprey --no-index --find-link=wheelhouse
```
Hopefully that should let you temporarily work around the issue and install osprey.

**Comment by jkleinj** [comment]
Thanks for the reply.
It worked now perfectly in the original form. I think the problem was that I had downloaded the tar.gz source package previously instead of the osprey zip package.
