### ISSUE TITLE
Where did you get the ICC8's secondary structure PDB file from?

### ISSUE THREAD

**Issue by gusennan** [donaldlab/OSPREY3#78]
I was going through the tutorial and saw that the input file was `1CC8.ss.pdb`.  I'm new to this and was wondering where you got this file.  1CC8 [on the PDB](https://www.rcsb.org/pdb/explore/structureCluster.do?structureId=1CC8) doesn't seem to have a link to it--I may have missed it though. 

Thanks!

**Comment by markhallen369** [comment]
If I remember correctly, I generated this by adding the secondary structure information from the PDB version of 1CC8 to a curated version of the 1CC8 structure that Kyle and Pablo generated for one of their iMinDEE (PLoS Comp Bio 2012) test cases.  

Mark

**Comment by gusennan** [comment]
Thanks!  I'll see if I can track more info down in that paper.
