### ISSUE TITLE
pip2 removes --use-wheel option in 10.1

### ISSUE THREAD

**Issue by gusennan** [donaldlab/OSPREY3#88]
The latest version of pip2 is 18.0.  Version 10.1 [removes the --use-wheel](https://pip.pypa.io/en/stable/news/#b1-2018-03-31) option and uses wheels by default. So this flag used in install.sh causes an error.  One possible check in install.sh could be:

```bash
wheel_flag="--use-wheel"
version=$(pip2 --version | cut --delimiter=' ' --fields 2 | cut --delimiter='.' --fields 1,2)
if python -c "exit($version > 10)"
then
  wheel_flag=""
fi
pip2 install --user osprey --no-index $wheel_flag --find-link=wheelhouse
```
Might be worth just checking if it works simply omitting it on older versions of pip2 (like 8.1) before adding in a conditional check.

**Comment by cuchaz** [comment]
I think the `--use-wheel` flag [was dropped from the install script fairly recently](https://github.com/donaldlab/OSPREY3/commit/1424fdc8b12f026a3a0e37bc47ba5bf5608687c7).

Are you suggesting we add it back in for older versions of pip2?

Btw, my pip2 9.0.1 doesn't seem to use offer the `--use-wheel` option either, so the flag might have been removed even earlier than v 10.1.

**Comment by gusennan** [comment]
Oh, cool.  No, I'm not suggesting that.  The latest release package still has the older install.sh script, this is where I ran into it.  I think i saw --use-wheel was deprecated in the 7.* level but only removed in 10.1

**Comment by cuchaz** [comment]
Ok. The master branch is pretty far ahead of the 3.0 release now. It may be time to start thinking about releasing a 3.1 version. There's a ton of new stuff to put out there, like this install.sh fix, but also tons of new design algorithm implementations.
