### ISSUE TITLE
K* example script

### ISSUE THREAD

**Issue by gusennan** [donaldlab/OSPREY3#89]
Hi, sorry for spamming, if you'd prefer I email questions let me know. 

I'm trying to run the K* example script [here](https://raw.githubusercontent.com/donaldlab/OSPREY3/master/examples/python.KStar/kstar.py) on the latest release (3.0 beta) and ran into this error:

```
>>> parallelism=osprey.Parallelism(cpuCores=2)
>>> ecalc = osprey.EnergyCalculator(complexConfSpace, ffparams, parallelism=parallelism)
>>> kstar = osprey.KStar(proteinConfSpace, ligandConfSpace, complexConfSpace, epsilon=0.99, writeSequencesToConsole=True, writeSequencesToFile='kstar.results.tsv')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: KStar() takes at least 6 arguments (6 given)
>>> kstar = osprey.KStar(
...     proteinConfSpace,
...     ligandConfSpace,
...     complexConfSpace,
...     epsilon=0.99, # you proabably want something more precise in your real designs
...     writeSequencesToConsole=True,
...     writeSequencesToFile='kstar.results.tsv'
... )
Traceback (most recent call last):
  File "<stdin>", line 7, in <module>
TypeError: KStar() takes at least 6 arguments (6 given)
```
Strange error message! I searched the repo and didn't find anything with this message, is it a JPype thing?  I confirmed that just running the script throws this error too.

**Comment by gusennan** [comment]
By the way, I really like being able to run this with python.

**Comment by cuchaz** [comment]
Nah, github issues are fine. That way, the resolutions are searchable for posterity. =)

Running example scripts from the master branch against the 3.0 release probably won't work anymore. The master branch has progressed a lot since the 3.0 release. The example scripts in 3.0 zip file you downloaded to install osprey should work though. eg. `examples/python.KStar/kstar.py`

**Comment by gusennan** [comment]
Yup, that was it.  Thank you!
