### ISSUE TITLE
import Osprey  Error

### ISSUE THREAD

**Issue by sinuxs** [donaldlab/OSPREY3#90]
Hello Dear Guys!
when i do the instruction after installation i have the error below:
Traceback (most recent call last):
  File "analyzeSequence.py", line 2, in <module>
    import osprey
ImportError: No module named osprey
What should i do with that??

**Comment by sinuxs** [comment]
Dear @gusennan thank you for your consideration,,
my python version is 2.7 and the java version which my ubuntu 18.04 machine use is
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-0ubuntu0.16.04.1-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)

**Comment by t-k26** [comment]
Dear All,

I have come across the same import osprey error, which however, can't be solved using the python interpeter (IDLE).
In addition, when I use the Jupyter QTConsole, I can import Osprey, but I get the following error message upon starting it:
import osprey

osprey.start()

UnsupportedOperationTraceback (most recent call last)
<ipython-input-2-9c131cbb2328> in <module>()
----> 1 osprey.start()

/Users/teresak/.local/lib/python2.7/site-packages/osprey/__init__.pyc in start(heapSizeMiB, enableAssertions, stackSizeMiB, garbageSizeMiB)
     74 
     75         # disable buffered output on stdout, so python log messages line up with java log messages
---> 76         sys.stdout = os.fdopen(sys.stdout.fileno(), 'w', 0)
     77 
     78         # setup a global exception handler to show java exception info

UnsupportedOperation: fileno

Additional Infos:
Operating System: Mac OS High Sierra 10.13.4
Python: 2.7.16 (2.7.6 in QT Console)
Java: java version "12.0.2" 2019-07-16
Java(TM) SE Runtime Environment (build 12.0.2+10)
Java HotSpot(TM) 64-Bit Server VM (build 12.0.2+10, mixed mode, sharing)
Please note: I have also got jdk1.8.0_212 and 1.6.0.jdk available als virtual machines and Osprey 2.2 beta runs perfectly fine

Any help is greatly appreciated!

**Comment by cuchaz** [comment]
Hi there, t0k26.

Currently Osprey isn't supported in the Python IDLE environment. The IDLE environment apparently changes the way interprocess communication works, so that breaks our Python/Java integration.

You should be able to run Osprey if you use one of the standard Python 2.7 distributions, like this one:
https://www.python.org/downloads/release/python-2716/
