### ISSUE TITLE
generating a custom template library

### ISSUE THREAD

**Issue by castephens** [donaldlab/OSPREY3#98]
Hi, 

I'm trying to the parameters of a small molecule in my pdb file to the template library. I don't understand the formatting shown in /examples/python.GMEC/templateLibrary.py. Is there any more specific documentation on how to format the custom template, as in what information is in each column?

**Comment by cuchaz** [comment]
Hello,

The template library file format used by OSPREY mimics the output of the [AmberTools LEaP](http://ambermd.org/doc12/AmberTools13.pdf) program. We have no documentation in OSPREY for this format, but you can look at the documentation for AmberTools.

You can also look at our [built-in template library for natural amino acids](https://github.com/donaldlab/OSPREY3/blob/master/resources/config/all_amino94.in) for more examples.

**Comment by castephens** [comment]
Thanks, I used LEaP to generate a topology and coordinate file for my small molecule, but none of the information in those files resembles the format of the template library file. Is there a specific output file from LEaP that OSPREY mimics other than the files I mentioned?

**Comment by cuchaz** [comment]
Sorry, I don't actually know much AmberTools or how to use them. I do know that OSPREY only reads columns 2, 3, 5 and 11 out of that file and ignores all the rest of the columns. Here's what those columns do:

 * 2: the name of the atom
 * 3: the AMBER forcefield type for the atom
 * 5: index of the bonded atom (refers to column 1, which holds the atom indices)
 * 11: partial charge of the atom for the AMBER forcefield

Here's the relevant [source code for the template file parser](https://github.com/donaldlab/OSPREY3/blob/master/src/edu/duke/cs/osprey/restypes/TemplateParser.java#L119) if that helps.

There are also some loop records for closed rings in eg PRO, PHE. For example, here's a LOOP section for PHE:
```
LOOP                                                            
CG CD2 
```

Here's an example of the [coords files for all the built-in amino acids](https://github.com/donaldlab/OSPREY3/blob/master/resources/config/all_amino_coords.in) too. For that file, only columns 1,2,3,4 are read by OSPREY. The rest of the columns are ignored. They are:

 * 1: atom name
 * 2: x coord
 * 3: y coord
 * 4: z coord

Here's the [source code for parsing the template coords](https://github.com/donaldlab/OSPREY3/blob/master/src/edu/duke/cs/osprey/restypes/TemplateCoordsParser.java#L155) if that helps.

**Comment by castephens** [comment]
ok, thats helpful. I'm not sure what you mean by "Amber forcefield type", can you explain or point to some online documentation?

**Comment by castephens** [comment]
Ok, thats helpful, thanks! For the formatting of the "define our custom templates", it actually comes from a file (.prepi or .mol2) made using antechamber (http://ambermd.org/tutorials/pengfei/index.htm) to use for LEaP.
